import { Typography } from "@/components/Typography";
import "./auth.styles.css";
import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="h-screen w-full flex">
      <div className="main-auth-container w-1/2 h-full flex justify-center items-center flex-col">
        <Typography variant="h1" className="text-white">
          Sistema de Gestión de Fincas
        </Typography>
        <Typography variant="p" className="text-white">
          Santa Finca te ayuda a gestionar tu finca
        </Typography>
      </div>
      <div className="w-1/2 h-full flex justify-center items-center">
        <div className="w-1/2 p-6 flex justify-center items-center">
          {children}
        </div>
      </div>
    </main>
  );
}
