import type { Metadata } from "next";

import PublicNavigation from "@/components/Nav/PublicNavigation";
import PublicFooter from "@/components/footer/PublicFooter";

export const metadata: Metadata = {
  title: "Home - Santa Finca",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col min-h-screen">
      <PublicNavigation />

      <main className="flex-grow w-full">{children}</main>

      <PublicFooter />
    </div>
  );
}
